import React from "react";
import { useNavigate } from "react-router-dom";
import { Text } from "components";
import "./index.css";

const Navbar = () => {
  const navigate = useNavigate();

  return (
    <div className="footer">
      <div className="footer-text">

      Website created by Alex Burmeister, Fall 2023. <br />  
      DES 070 with Professor Jenny Kowalski,
      Lehigh Universtiy. <br /> All images are from Unsplash.com.
      All text generated by Chat GPT.
     
      {/* <div className="icon-home"> 
          <button onClick={() => navigate("/landingpage")}>La Piazza Sul Tetto</button> 
      </div>


      <div className="navbar-icons">
        <div className="icon-reservations"> 
          <button onClick={() => navigate("/reservations")}>Reservations</button> 
        </div>
        <div className="icon-menu"> 
          <button onClick={() => navigate("/menu")}>Menu</button>
        </div>
        <div className="icon-visualmenu"> 
          <button onClick={() => navigate("/visualmenu")}>Visual Menu</button>
        </div>
        <div className="icon-faqs"> 
          <button onClick={() => navigate("/faqs")}>FAQs</button>
        </div>
      </div> */}

      </div>
    </div>
  );
};


export default Navbar;
